// Code generated by "stringer -type=ContactType"; DO NOT EDIT.

package schemas

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ContactTypeUnknown-0]
	_ = x[ContactTypePersonal-1]
	_ = x[ContactTypeOfficial-2]
}

const _ContactType_name = "ContactTypeUnknownContactTypePersonalContactTypeOfficial"

var _ContactType_index = [...]uint8{0, 18, 37, 56}

func (i ContactType) String() string {
	if i >= ContactType(len(_ContactType_index)-1) {
		return "ContactType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ContactType_name[_ContactType_index[i]:_ContactType_index[i+1]]
}
