// Code generated by "stringer -type=ContactGender"; DO NOT EDIT.

package schemas

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ContactGenderUnknown-0]
	_ = x[ContactGenderMale-1]
	_ = x[ContactGenderFemale-2]
}

const _ContactGender_name = "ContactGenderUnknownContactGenderMaleContactGenderFemale"

var _ContactGender_index = [...]uint8{0, 20, 37, 56}

func (i ContactGender) String() string {
	if i >= ContactGender(len(_ContactGender_index)-1) {
		return "ContactGender(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ContactGender_name[_ContactGender_index[i]:_ContactGender_index[i+1]]
}
