// Code generated by "stringer -type=FriendshipType"; DO NOT EDIT.

package schemas

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FriendshipTypeUnknown-0]
	_ = x[FriendshipTypeConfirm-1]
	_ = x[FriendshipTypeReceive-2]
	_ = x[FriendshipTypeVerify-3]
}

const _FriendshipType_name = "FriendshipTypeUnknownFriendshipTypeConfirmFriendshipTypeReceiveFriendshipTypeVerify"

var _FriendshipType_index = [...]uint8{0, 21, 42, 63, 83}

func (i FriendshipType) String() string {
	if i >= FriendshipType(len(_FriendshipType_index)-1) {
		return "FriendshipType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FriendshipType_name[_FriendshipType_index[i]:_FriendshipType_index[i+1]]
}
