// Code generated by "stringer -type=ImageType"; DO NOT EDIT.

package schemas

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ImageTypeUnknown-0]
	_ = x[ImageTypeThumbnail-1]
	_ = x[ImageTypeHD-2]
	_ = x[ImageTypeArtwork-3]
}

const _ImageType_name = "ImageTypeUnknownImageTypeThumbnailImageTypeHDImageTypeArtwork"

var _ImageType_index = [...]uint8{0, 16, 34, 45, 61}

func (i ImageType) String() string {
	if i >= ImageType(len(_ImageType_index)-1) {
		return "ImageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ImageType_name[_ImageType_index[i]:_ImageType_index[i+1]]
}
