// Code generated by "stringer -type=PuppetEventName"; DO NOT EDIT.

package schemas

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PuppetEventNameUnknown-0]
	_ = x[PuppetEventNameFriendShipConfirm-1]
	_ = x[PuppetEventNameFriendShipReceive-2]
	_ = x[PuppetEventNameFriendShipVerify-3]
	_ = x[PuppetEventNameLogin-4]
	_ = x[PuppetEventNameLogout-5]
	_ = x[PuppetEventNameMessage-6]
	_ = x[PuppetEventNameRoomInvite-7]
	_ = x[PuppetEventNameRoomJoin-8]
	_ = x[PuppetEventNameRoomLeave-9]
	_ = x[PuppetEventNameRoomTopic-10]
	_ = x[PuppetEventNameScan-11]
	_ = x[PuppetEventNameDong-12]
	_ = x[PuppetEventNameError-13]
	_ = x[PuppetEventNameHeartbeat-14]
	_ = x[PuppetEventNameReady-15]
	_ = x[PuppetEventNameReset-16]
	_ = x[PuppetEventNameStop-17]
	_ = x[PuppetEventNameStart-18]
}

const _PuppetEventName_name = "PuppetEventNameUnknownPuppetEventNameFriendShipConfirmPuppetEventNameFriendShipReceivePuppetEventNameFriendShipVerifyPuppetEventNameLoginPuppetEventNameLogoutPuppetEventNameMessagePuppetEventNameRoomInvitePuppetEventNameRoomJoinPuppetEventNameRoomLeavePuppetEventNameRoomTopicPuppetEventNameScanPuppetEventNameDongPuppetEventNameErrorPuppetEventNameHeartbeatPuppetEventNameReadyPuppetEventNameResetPuppetEventNameStopPuppetEventNameStart"

var _PuppetEventName_index = [...]uint16{0, 22, 54, 86, 117, 137, 158, 180, 205, 228, 252, 276, 295, 314, 334, 358, 378, 398, 417, 437}

func (i PuppetEventName) String() string {
	if i >= PuppetEventName(len(_PuppetEventName_index)-1) {
		return "PuppetEventName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PuppetEventName_name[_PuppetEventName_index[i]:_PuppetEventName_index[i+1]]
}
