// Code generated by "stringer -type=PuppetEventName"; DO NOT EDIT.

package schemas

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PuppetEventNameUnknown-0]
	_ = x[PuppetEventNameFriendship-1]
	_ = x[PuppetEventNameLogin-2]
	_ = x[PuppetEventNameLogout-3]
	_ = x[PuppetEventNameMessage-4]
	_ = x[PuppetEventNameRoomInvite-5]
	_ = x[PuppetEventNameRoomJoin-6]
	_ = x[PuppetEventNameRoomLeave-7]
	_ = x[PuppetEventNameRoomTopic-8]
	_ = x[PuppetEventNameScan-9]
	_ = x[PuppetEventNameDong-10]
	_ = x[PuppetEventNameError-11]
	_ = x[PuppetEventNameHeartbeat-12]
	_ = x[PuppetEventNameReady-13]
	_ = x[PuppetEventNameReset-14]
	_ = x[PuppetEventNameDirty-15]
	_ = x[PuppetEventNameStop-16]
	_ = x[PuppetEventNameStart-17]
}

const _PuppetEventName_name = "PuppetEventNameUnknownPuppetEventNameFriendshipPuppetEventNameLoginPuppetEventNameLogoutPuppetEventNameMessagePuppetEventNameRoomInvitePuppetEventNameRoomJoinPuppetEventNameRoomLeavePuppetEventNameRoomTopicPuppetEventNameScanPuppetEventNameDongPuppetEventNameErrorPuppetEventNameHeartbeatPuppetEventNameReadyPuppetEventNameResetPuppetEventNameDirtyPuppetEventNameStopPuppetEventNameStart"

var _PuppetEventName_index = [...]uint16{0, 22, 47, 67, 88, 110, 135, 158, 182, 206, 225, 244, 264, 288, 308, 328, 348, 367, 387}

func (i PuppetEventName) String() string {
	if i >= PuppetEventName(len(_PuppetEventName_index)-1) {
		return "PuppetEventName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PuppetEventName_name[_PuppetEventName_index[i]:_PuppetEventName_index[i+1]]
}
