// Code generated by "stringer -type=PuppetEventName"; DO NOT EDIT.

package schemas

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PuppetEventNameUnknown-0]
	_ = x[PuppetEventNameFriendShipConfirm-1]
	_ = x[PuppetEventNameFriendShipReceive-2]
	_ = x[PuppetEventNameFriendShipVerify-3]
	_ = x[PuppetEventNameFriendShip-4]
	_ = x[PuppetEventNameLogin-5]
	_ = x[PuppetEventNameLogout-6]
	_ = x[PuppetEventNameMessage-7]
	_ = x[PuppetEventNameRoomInvite-8]
	_ = x[PuppetEventNameRoomJoin-9]
	_ = x[PuppetEventNameRoomLeave-10]
	_ = x[PuppetEventNameRoomTopic-11]
	_ = x[PuppetEventNameScan-12]
	_ = x[PuppetEventNameDong-13]
	_ = x[PuppetEventNameError-14]
	_ = x[PuppetEventNameHeartbeat-15]
	_ = x[PuppetEventNameReady-16]
	_ = x[PuppetEventNameReset-17]
	_ = x[PuppetEventNameStop-18]
	_ = x[PuppetEventNameStart-19]
}

const _PuppetEventName_name = "PuppetEventNameUnknownPuppetEventNameFriendShipConfirmPuppetEventNameFriendShipReceivePuppetEventNameFriendShipVerifyPuppetEventNameFriendShipPuppetEventNameLoginPuppetEventNameLogoutPuppetEventNameMessagePuppetEventNameRoomInvitePuppetEventNameRoomJoinPuppetEventNameRoomLeavePuppetEventNameRoomTopicPuppetEventNameScanPuppetEventNameDongPuppetEventNameErrorPuppetEventNameHeartbeatPuppetEventNameReadyPuppetEventNameResetPuppetEventNameStopPuppetEventNameStart"

var _PuppetEventName_index = [...]uint16{0, 22, 54, 86, 117, 142, 162, 183, 205, 230, 253, 277, 301, 320, 339, 359, 383, 403, 423, 442, 462}

func (i PuppetEventName) String() string {
	if i >= PuppetEventName(len(_PuppetEventName_index)-1) {
		return "PuppetEventName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PuppetEventName_name[_PuppetEventName_index[i]:_PuppetEventName_index[i+1]]
}
