// Code generated by "stringer -type=ScanStatus"; DO NOT EDIT.

package schemas

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ScanStatusUnknown-0]
	_ = x[ScanStatusCancel-1]
	_ = x[ScanStatusWaiting-2]
	_ = x[ScanStatusScanned-3]
	_ = x[ScanStatusConfirmed-4]
	_ = x[ScanStatusTimeout-5]
}

const _ScanStatus_name = "ScanStatusUnknownScanStatusCancelScanStatusWaitingScanStatusScannedScanStatusConfirmedScanStatusTimeout"

var _ScanStatus_index = [...]uint8{0, 17, 33, 50, 67, 86, 103}

func (i ScanStatus) String() string {
	if i >= ScanStatus(len(_ScanStatus_index)-1) {
		return "ScanStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScanStatus_name[_ScanStatus_index[i]:_ScanStatus_index[i+1]]
}
