// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package puppet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (m *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(m, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

type StartResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartResponse) Reset()         { *m = StartResponse{} }
func (m *StartResponse) String() string { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()    {}
func (*StartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

func (m *StartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse.Unmarshal(m, b)
}
func (m *StartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse.Marshal(b, m, deterministic)
}
func (m *StartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse.Merge(m, src)
}
func (m *StartResponse) XXX_Size() int {
	return xxx_messageInfo_StartResponse.Size(m)
}
func (m *StartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse proto.InternalMessageInfo

type StopRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{2}
}

func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (m *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(m, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

type StopResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopResponse) Reset()         { *m = StopResponse{} }
func (m *StopResponse) String() string { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()    {}
func (*StopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{3}
}

func (m *StopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopResponse.Unmarshal(m, b)
}
func (m *StopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopResponse.Marshal(b, m, deterministic)
}
func (m *StopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopResponse.Merge(m, src)
}
func (m *StopResponse) XXX_Size() int {
	return xxx_messageInfo_StopResponse.Size(m)
}
func (m *StopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopResponse proto.InternalMessageInfo

type VersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{4}
}

func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (m *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(m, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{5}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LogoutRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{6}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{7}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

type DingRequest struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DingRequest) Reset()         { *m = DingRequest{} }
func (m *DingRequest) String() string { return proto.CompactTextString(m) }
func (*DingRequest) ProtoMessage()    {}
func (*DingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{8}
}

func (m *DingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DingRequest.Unmarshal(m, b)
}
func (m *DingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DingRequest.Marshal(b, m, deterministic)
}
func (m *DingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DingRequest.Merge(m, src)
}
func (m *DingRequest) XXX_Size() int {
	return xxx_messageInfo_DingRequest.Size(m)
}
func (m *DingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DingRequest proto.InternalMessageInfo

func (m *DingRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type DingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DingResponse) Reset()         { *m = DingResponse{} }
func (m *DingResponse) String() string { return proto.CompactTextString(m) }
func (*DingResponse) ProtoMessage()    {}
func (*DingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{9}
}

func (m *DingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DingResponse.Unmarshal(m, b)
}
func (m *DingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DingResponse.Marshal(b, m, deterministic)
}
func (m *DingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DingResponse.Merge(m, src)
}
func (m *DingResponse) XXX_Size() int {
	return xxx_messageInfo_DingResponse.Size(m)
}
func (m *DingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DingResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StartRequest)(nil), "wechaty.puppet.StartRequest")
	proto.RegisterType((*StartResponse)(nil), "wechaty.puppet.StartResponse")
	proto.RegisterType((*StopRequest)(nil), "wechaty.puppet.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "wechaty.puppet.StopResponse")
	proto.RegisterType((*VersionRequest)(nil), "wechaty.puppet.VersionRequest")
	proto.RegisterType((*VersionResponse)(nil), "wechaty.puppet.VersionResponse")
	proto.RegisterType((*LogoutRequest)(nil), "wechaty.puppet.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "wechaty.puppet.LogoutResponse")
	proto.RegisterType((*DingRequest)(nil), "wechaty.puppet.DingRequest")
	proto.RegisterType((*DingResponse)(nil), "wechaty.puppet.DingResponse")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0x31, 0x4f, 0xc4, 0x30,
	0x0c, 0x85, 0x75, 0x12, 0x02, 0xe1, 0xe3, 0x72, 0x55, 0xa6, 0x8e, 0xd0, 0x09, 0x09, 0xb5, 0x1d,
	0xf8, 0x07, 0x88, 0x0d, 0x58, 0x5a, 0x89, 0x81, 0x2d, 0x2d, 0x56, 0x9a, 0x81, 0x38, 0x24, 0x0e,
	0x88, 0x7f, 0x8f, 0xda, 0x24, 0x9d, 0x62, 0xbf, 0xf7, 0x39, 0x2f, 0x31, 0xc0, 0xa4, 0x02, 0x76,
	0xce, 0x13, 0x93, 0x14, 0xbf, 0x38, 0x2f, 0x8a, 0xff, 0x3a, 0x17, 0x9d, 0x43, 0x6e, 0x04, 0xdc,
	0x8c, 0xac, 0x3c, 0x0f, 0xf8, 0x1d, 0x31, 0x70, 0x73, 0x86, 0x53, 0xee, 0x83, 0x23, 0x1b, 0xb0,
	0x39, 0xc1, 0x71, 0x64, 0x72, 0xc5, 0xdf, 0xf8, 0xb5, 0xcd, 0x76, 0x05, 0xe2, 0x1d, 0x7d, 0x30,
	0x64, 0x0b, 0xf1, 0x00, 0xe7, 0x5d, 0x49, 0x90, 0xac, 0xe1, 0xea, 0x27, 0x49, 0xf5, 0xe1, 0xf6,
	0x70, 0x7f, 0x3d, 0x94, 0x76, 0x8d, 0x7b, 0x25, 0x4d, 0x71, 0xcf, 0xaf, 0x40, 0x14, 0x21, 0x27,
	0xdc, 0xc1, 0xf1, 0xd9, 0x58, 0x9d, 0x01, 0x29, 0xe1, 0xe2, 0x53, 0xb1, 0xca, 0x17, 0x6d, 0xf5,
	0xfa, 0xa8, 0x84, 0xa4, 0x91, 0xa7, 0xb7, 0x8f, 0x17, 0x6d, 0x78, 0x89, 0x53, 0x37, 0xd3, 0x57,
	0x9f, 0x7f, 0xdc, 0x6b, 0x6a, 0x4b, 0x99, 0xcf, 0x36, 0x2d, 0xa1, 0x5d, 0x28, 0xb0, 0xc1, 0x5e,
	0xa3, 0x45, 0xaf, 0x18, 0xf7, 0x89, 0x64, 0x4f, 0x97, 0xdb, 0xea, 0x1e, 0xff, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x65, 0xd2, 0x3c, 0xf8, 0x48, 0x01, 0x00, 0x00,
}
