// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package puppet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED  MessageType = 0
	MessageType_MESSAGE_TYPE_ATTACHMENT   MessageType = 1
	MessageType_MESSAGE_TYPE_AUDIO        MessageType = 2
	MessageType_MESSAGE_TYPE_CONTACT      MessageType = 3
	MessageType_MESSAGE_TYPE_EMOTICON     MessageType = 4
	MessageType_MESSAGE_TYPE_IMAGE        MessageType = 5
	MessageType_MESSAGE_TYPE_TEXT         MessageType = 6
	MessageType_MESSAGE_TYPE_VIDEO        MessageType = 7
	MessageType_MESSAGE_TYPE_CHAT_HISTORY MessageType = 8
	MessageType_MESSAGE_TYPE_LOCATION     MessageType = 9
	MessageType_MESSAGE_TYPE_MINI_PROGRAM MessageType = 10
	MessageType_MESSAGE_TYPE_TRANSFER     MessageType = 11
	MessageType_MESSAGE_TYPE_RED_ENVELOPE MessageType = 12
	MessageType_MESSAGE_TYPE_RECALLED     MessageType = 13
	MessageType_MESSAGE_TYPE_URL          MessageType = 14
)

var MessageType_name = map[int32]string{
	0:  "MESSAGE_TYPE_UNSPECIFIED",
	1:  "MESSAGE_TYPE_ATTACHMENT",
	2:  "MESSAGE_TYPE_AUDIO",
	3:  "MESSAGE_TYPE_CONTACT",
	4:  "MESSAGE_TYPE_EMOTICON",
	5:  "MESSAGE_TYPE_IMAGE",
	6:  "MESSAGE_TYPE_TEXT",
	7:  "MESSAGE_TYPE_VIDEO",
	8:  "MESSAGE_TYPE_CHAT_HISTORY",
	9:  "MESSAGE_TYPE_LOCATION",
	10: "MESSAGE_TYPE_MINI_PROGRAM",
	11: "MESSAGE_TYPE_TRANSFER",
	12: "MESSAGE_TYPE_RED_ENVELOPE",
	13: "MESSAGE_TYPE_RECALLED",
	14: "MESSAGE_TYPE_URL",
}

var MessageType_value = map[string]int32{
	"MESSAGE_TYPE_UNSPECIFIED":  0,
	"MESSAGE_TYPE_ATTACHMENT":   1,
	"MESSAGE_TYPE_AUDIO":        2,
	"MESSAGE_TYPE_CONTACT":      3,
	"MESSAGE_TYPE_EMOTICON":     4,
	"MESSAGE_TYPE_IMAGE":        5,
	"MESSAGE_TYPE_TEXT":         6,
	"MESSAGE_TYPE_VIDEO":        7,
	"MESSAGE_TYPE_CHAT_HISTORY": 8,
	"MESSAGE_TYPE_LOCATION":     9,
	"MESSAGE_TYPE_MINI_PROGRAM": 10,
	"MESSAGE_TYPE_TRANSFER":     11,
	"MESSAGE_TYPE_RED_ENVELOPE": 12,
	"MESSAGE_TYPE_RECALLED":     13,
	"MESSAGE_TYPE_URL":          14,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type ImageType int32

const (
	ImageType_IMAGE_TYPE_UNSPECIFIED ImageType = 0
	ImageType_IMAGE_TYPE_THUMBNAIL   ImageType = 1
	ImageType_IMAGE_TYPE_HD          ImageType = 2
	ImageType_IMAGE_TYPE_ARTWORK     ImageType = 3
)

var ImageType_name = map[int32]string{
	0: "IMAGE_TYPE_UNSPECIFIED",
	1: "IMAGE_TYPE_THUMBNAIL",
	2: "IMAGE_TYPE_HD",
	3: "IMAGE_TYPE_ARTWORK",
}

var ImageType_value = map[string]int32{
	"IMAGE_TYPE_UNSPECIFIED": 0,
	"IMAGE_TYPE_THUMBNAIL":   1,
	"IMAGE_TYPE_HD":          2,
	"IMAGE_TYPE_ARTWORK":     3,
}

func (x ImageType) String() string {
	return proto.EnumName(ImageType_name, int32(x))
}

func (ImageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

type MessagePayloadRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagePayloadRequest) Reset()         { *m = MessagePayloadRequest{} }
func (m *MessagePayloadRequest) String() string { return proto.CompactTextString(m) }
func (*MessagePayloadRequest) ProtoMessage()    {}
func (*MessagePayloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *MessagePayloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagePayloadRequest.Unmarshal(m, b)
}
func (m *MessagePayloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagePayloadRequest.Marshal(b, m, deterministic)
}
func (m *MessagePayloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagePayloadRequest.Merge(m, src)
}
func (m *MessagePayloadRequest) XXX_Size() int {
	return xxx_messageInfo_MessagePayloadRequest.Size(m)
}
func (m *MessagePayloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagePayloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessagePayloadRequest proto.InternalMessageInfo

func (m *MessagePayloadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessagePayloadResponse struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename             string      `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Text                 string      `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp            uint64      `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type                 MessageType `protobuf:"varint,5,opt,name=type,proto3,enum=wechaty.puppet.MessageType" json:"type,omitempty"`
	FromId               string      `protobuf:"bytes,6,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	RoomId               string      `protobuf:"bytes,7,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ToId                 string      `protobuf:"bytes,8,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	MentionIds           []string    `protobuf:"bytes,9,rep,name=mention_ids,json=mentionIds,proto3" json:"mention_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MessagePayloadResponse) Reset()         { *m = MessagePayloadResponse{} }
func (m *MessagePayloadResponse) String() string { return proto.CompactTextString(m) }
func (*MessagePayloadResponse) ProtoMessage()    {}
func (*MessagePayloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *MessagePayloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagePayloadResponse.Unmarshal(m, b)
}
func (m *MessagePayloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagePayloadResponse.Marshal(b, m, deterministic)
}
func (m *MessagePayloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagePayloadResponse.Merge(m, src)
}
func (m *MessagePayloadResponse) XXX_Size() int {
	return xxx_messageInfo_MessagePayloadResponse.Size(m)
}
func (m *MessagePayloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagePayloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessagePayloadResponse proto.InternalMessageInfo

func (m *MessagePayloadResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessagePayloadResponse) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *MessagePayloadResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MessagePayloadResponse) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessagePayloadResponse) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (m *MessagePayloadResponse) GetFromId() string {
	if m != nil {
		return m.FromId
	}
	return ""
}

func (m *MessagePayloadResponse) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *MessagePayloadResponse) GetToId() string {
	if m != nil {
		return m.ToId
	}
	return ""
}

func (m *MessagePayloadResponse) GetMentionIds() []string {
	if m != nil {
		return m.MentionIds
	}
	return nil
}

type MessageImageRequest struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 ImageType `protobuf:"varint,2,opt,name=type,proto3,enum=wechaty.puppet.ImageType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MessageImageRequest) Reset()         { *m = MessageImageRequest{} }
func (m *MessageImageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageImageRequest) ProtoMessage()    {}
func (*MessageImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *MessageImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageImageRequest.Unmarshal(m, b)
}
func (m *MessageImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageImageRequest.Marshal(b, m, deterministic)
}
func (m *MessageImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageImageRequest.Merge(m, src)
}
func (m *MessageImageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageImageRequest.Size(m)
}
func (m *MessageImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageImageRequest proto.InternalMessageInfo

func (m *MessageImageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageImageRequest) GetType() ImageType {
	if m != nil {
		return m.Type
	}
	return ImageType_IMAGE_TYPE_UNSPECIFIED
}

type MessageImageResponse struct {
	Filebox              string   `protobuf:"bytes,1,opt,name=filebox,proto3" json:"filebox,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageImageResponse) Reset()         { *m = MessageImageResponse{} }
func (m *MessageImageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageImageResponse) ProtoMessage()    {}
func (*MessageImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *MessageImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageImageResponse.Unmarshal(m, b)
}
func (m *MessageImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageImageResponse.Marshal(b, m, deterministic)
}
func (m *MessageImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageImageResponse.Merge(m, src)
}
func (m *MessageImageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageImageResponse.Size(m)
}
func (m *MessageImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageImageResponse proto.InternalMessageInfo

func (m *MessageImageResponse) GetFilebox() string {
	if m != nil {
		return m.Filebox
	}
	return ""
}

type MessageContactRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageContactRequest) Reset()         { *m = MessageContactRequest{} }
func (m *MessageContactRequest) String() string { return proto.CompactTextString(m) }
func (*MessageContactRequest) ProtoMessage()    {}
func (*MessageContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *MessageContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageContactRequest.Unmarshal(m, b)
}
func (m *MessageContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageContactRequest.Marshal(b, m, deterministic)
}
func (m *MessageContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageContactRequest.Merge(m, src)
}
func (m *MessageContactRequest) XXX_Size() int {
	return xxx_messageInfo_MessageContactRequest.Size(m)
}
func (m *MessageContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageContactRequest proto.InternalMessageInfo

func (m *MessageContactRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessageContactResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageContactResponse) Reset()         { *m = MessageContactResponse{} }
func (m *MessageContactResponse) String() string { return proto.CompactTextString(m) }
func (*MessageContactResponse) ProtoMessage()    {}
func (*MessageContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *MessageContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageContactResponse.Unmarshal(m, b)
}
func (m *MessageContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageContactResponse.Marshal(b, m, deterministic)
}
func (m *MessageContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageContactResponse.Merge(m, src)
}
func (m *MessageContactResponse) XXX_Size() int {
	return xxx_messageInfo_MessageContactResponse.Size(m)
}
func (m *MessageContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageContactResponse proto.InternalMessageInfo

func (m *MessageContactResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessageFileRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageFileRequest) Reset()         { *m = MessageFileRequest{} }
func (m *MessageFileRequest) String() string { return proto.CompactTextString(m) }
func (*MessageFileRequest) ProtoMessage()    {}
func (*MessageFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *MessageFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageFileRequest.Unmarshal(m, b)
}
func (m *MessageFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageFileRequest.Marshal(b, m, deterministic)
}
func (m *MessageFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageFileRequest.Merge(m, src)
}
func (m *MessageFileRequest) XXX_Size() int {
	return xxx_messageInfo_MessageFileRequest.Size(m)
}
func (m *MessageFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageFileRequest proto.InternalMessageInfo

func (m *MessageFileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessageFileResponse struct {
	Filebox              string   `protobuf:"bytes,1,opt,name=filebox,proto3" json:"filebox,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageFileResponse) Reset()         { *m = MessageFileResponse{} }
func (m *MessageFileResponse) String() string { return proto.CompactTextString(m) }
func (*MessageFileResponse) ProtoMessage()    {}
func (*MessageFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *MessageFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageFileResponse.Unmarshal(m, b)
}
func (m *MessageFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageFileResponse.Marshal(b, m, deterministic)
}
func (m *MessageFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageFileResponse.Merge(m, src)
}
func (m *MessageFileResponse) XXX_Size() int {
	return xxx_messageInfo_MessageFileResponse.Size(m)
}
func (m *MessageFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageFileResponse proto.InternalMessageInfo

func (m *MessageFileResponse) GetFilebox() string {
	if m != nil {
		return m.Filebox
	}
	return ""
}

type MessageMiniProgramRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageMiniProgramRequest) Reset()         { *m = MessageMiniProgramRequest{} }
func (m *MessageMiniProgramRequest) String() string { return proto.CompactTextString(m) }
func (*MessageMiniProgramRequest) ProtoMessage()    {}
func (*MessageMiniProgramRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *MessageMiniProgramRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageMiniProgramRequest.Unmarshal(m, b)
}
func (m *MessageMiniProgramRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageMiniProgramRequest.Marshal(b, m, deterministic)
}
func (m *MessageMiniProgramRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageMiniProgramRequest.Merge(m, src)
}
func (m *MessageMiniProgramRequest) XXX_Size() int {
	return xxx_messageInfo_MessageMiniProgramRequest.Size(m)
}
func (m *MessageMiniProgramRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageMiniProgramRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageMiniProgramRequest proto.InternalMessageInfo

func (m *MessageMiniProgramRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessageMiniProgramResponse struct {
	MiniProgram          string   `protobuf:"bytes,1,opt,name=mini_program,json=miniProgram,proto3" json:"mini_program,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageMiniProgramResponse) Reset()         { *m = MessageMiniProgramResponse{} }
func (m *MessageMiniProgramResponse) String() string { return proto.CompactTextString(m) }
func (*MessageMiniProgramResponse) ProtoMessage()    {}
func (*MessageMiniProgramResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *MessageMiniProgramResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageMiniProgramResponse.Unmarshal(m, b)
}
func (m *MessageMiniProgramResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageMiniProgramResponse.Marshal(b, m, deterministic)
}
func (m *MessageMiniProgramResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageMiniProgramResponse.Merge(m, src)
}
func (m *MessageMiniProgramResponse) XXX_Size() int {
	return xxx_messageInfo_MessageMiniProgramResponse.Size(m)
}
func (m *MessageMiniProgramResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageMiniProgramResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageMiniProgramResponse proto.InternalMessageInfo

func (m *MessageMiniProgramResponse) GetMiniProgram() string {
	if m != nil {
		return m.MiniProgram
	}
	return ""
}

type MessageUrlRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageUrlRequest) Reset()         { *m = MessageUrlRequest{} }
func (m *MessageUrlRequest) String() string { return proto.CompactTextString(m) }
func (*MessageUrlRequest) ProtoMessage()    {}
func (*MessageUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *MessageUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageUrlRequest.Unmarshal(m, b)
}
func (m *MessageUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageUrlRequest.Marshal(b, m, deterministic)
}
func (m *MessageUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageUrlRequest.Merge(m, src)
}
func (m *MessageUrlRequest) XXX_Size() int {
	return xxx_messageInfo_MessageUrlRequest.Size(m)
}
func (m *MessageUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageUrlRequest proto.InternalMessageInfo

func (m *MessageUrlRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessageUrlResponse struct {
	UrlLink              string   `protobuf:"bytes,1,opt,name=url_link,json=urlLink,proto3" json:"url_link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageUrlResponse) Reset()         { *m = MessageUrlResponse{} }
func (m *MessageUrlResponse) String() string { return proto.CompactTextString(m) }
func (*MessageUrlResponse) ProtoMessage()    {}
func (*MessageUrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}

func (m *MessageUrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageUrlResponse.Unmarshal(m, b)
}
func (m *MessageUrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageUrlResponse.Marshal(b, m, deterministic)
}
func (m *MessageUrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageUrlResponse.Merge(m, src)
}
func (m *MessageUrlResponse) XXX_Size() int {
	return xxx_messageInfo_MessageUrlResponse.Size(m)
}
func (m *MessageUrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageUrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageUrlResponse proto.InternalMessageInfo

func (m *MessageUrlResponse) GetUrlLink() string {
	if m != nil {
		return m.UrlLink
	}
	return ""
}

type MessageSendContactRequest struct {
	ConversationId       string   `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ContactId            string   `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageSendContactRequest) Reset()         { *m = MessageSendContactRequest{} }
func (m *MessageSendContactRequest) String() string { return proto.CompactTextString(m) }
func (*MessageSendContactRequest) ProtoMessage()    {}
func (*MessageSendContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{12}
}

func (m *MessageSendContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSendContactRequest.Unmarshal(m, b)
}
func (m *MessageSendContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSendContactRequest.Marshal(b, m, deterministic)
}
func (m *MessageSendContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSendContactRequest.Merge(m, src)
}
func (m *MessageSendContactRequest) XXX_Size() int {
	return xxx_messageInfo_MessageSendContactRequest.Size(m)
}
func (m *MessageSendContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSendContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSendContactRequest proto.InternalMessageInfo

func (m *MessageSendContactRequest) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *MessageSendContactRequest) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

type MessageSendContactResponse struct {
	// nullable
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MessageSendContactResponse) Reset()         { *m = MessageSendContactResponse{} }
func (m *MessageSendContactResponse) String() string { return proto.CompactTextString(m) }
func (*MessageSendContactResponse) ProtoMessage()    {}
func (*MessageSendContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{13}
}

func (m *MessageSendContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSendContactResponse.Unmarshal(m, b)
}
func (m *MessageSendContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSendContactResponse.Marshal(b, m, deterministic)
}
func (m *MessageSendContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSendContactResponse.Merge(m, src)
}
func (m *MessageSendContactResponse) XXX_Size() int {
	return xxx_messageInfo_MessageSendContactResponse.Size(m)
}
func (m *MessageSendContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSendContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSendContactResponse proto.InternalMessageInfo

func (m *MessageSendContactResponse) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

type MessageSendFileRequest struct {
	ConversationId       string   `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Filebox              string   `protobuf:"bytes,2,opt,name=filebox,proto3" json:"filebox,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageSendFileRequest) Reset()         { *m = MessageSendFileRequest{} }
func (m *MessageSendFileRequest) String() string { return proto.CompactTextString(m) }
func (*MessageSendFileRequest) ProtoMessage()    {}
func (*MessageSendFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{14}
}

func (m *MessageSendFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSendFileRequest.Unmarshal(m, b)
}
func (m *MessageSendFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSendFileRequest.Marshal(b, m, deterministic)
}
func (m *MessageSendFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSendFileRequest.Merge(m, src)
}
func (m *MessageSendFileRequest) XXX_Size() int {
	return xxx_messageInfo_MessageSendFileRequest.Size(m)
}
func (m *MessageSendFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSendFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSendFileRequest proto.InternalMessageInfo

func (m *MessageSendFileRequest) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *MessageSendFileRequest) GetFilebox() string {
	if m != nil {
		return m.Filebox
	}
	return ""
}

type MessageSendFileResponse struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MessageSendFileResponse) Reset()         { *m = MessageSendFileResponse{} }
func (m *MessageSendFileResponse) String() string { return proto.CompactTextString(m) }
func (*MessageSendFileResponse) ProtoMessage()    {}
func (*MessageSendFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{15}
}

func (m *MessageSendFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSendFileResponse.Unmarshal(m, b)
}
func (m *MessageSendFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSendFileResponse.Marshal(b, m, deterministic)
}
func (m *MessageSendFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSendFileResponse.Merge(m, src)
}
func (m *MessageSendFileResponse) XXX_Size() int {
	return xxx_messageInfo_MessageSendFileResponse.Size(m)
}
func (m *MessageSendFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSendFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSendFileResponse proto.InternalMessageInfo

func (m *MessageSendFileResponse) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

type MessageSendTextRequest struct {
	ConversationId       string   `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	MentonalIds          []string `protobuf:"bytes,3,rep,name=mentonal_ids,json=mentonalIds,proto3" json:"mentonal_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageSendTextRequest) Reset()         { *m = MessageSendTextRequest{} }
func (m *MessageSendTextRequest) String() string { return proto.CompactTextString(m) }
func (*MessageSendTextRequest) ProtoMessage()    {}
func (*MessageSendTextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{16}
}

func (m *MessageSendTextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSendTextRequest.Unmarshal(m, b)
}
func (m *MessageSendTextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSendTextRequest.Marshal(b, m, deterministic)
}
func (m *MessageSendTextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSendTextRequest.Merge(m, src)
}
func (m *MessageSendTextRequest) XXX_Size() int {
	return xxx_messageInfo_MessageSendTextRequest.Size(m)
}
func (m *MessageSendTextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSendTextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSendTextRequest proto.InternalMessageInfo

func (m *MessageSendTextRequest) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *MessageSendTextRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MessageSendTextRequest) GetMentonalIds() []string {
	if m != nil {
		return m.MentonalIds
	}
	return nil
}

type MessageSendTextResponse struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MessageSendTextResponse) Reset()         { *m = MessageSendTextResponse{} }
func (m *MessageSendTextResponse) String() string { return proto.CompactTextString(m) }
func (*MessageSendTextResponse) ProtoMessage()    {}
func (*MessageSendTextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{17}
}

func (m *MessageSendTextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSendTextResponse.Unmarshal(m, b)
}
func (m *MessageSendTextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSendTextResponse.Marshal(b, m, deterministic)
}
func (m *MessageSendTextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSendTextResponse.Merge(m, src)
}
func (m *MessageSendTextResponse) XXX_Size() int {
	return xxx_messageInfo_MessageSendTextResponse.Size(m)
}
func (m *MessageSendTextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSendTextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSendTextResponse proto.InternalMessageInfo

func (m *MessageSendTextResponse) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

type MessageSendMiniProgramRequest struct {
	ConversationId       string   `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MiniProgram          string   `protobuf:"bytes,2,opt,name=mini_program,json=miniProgram,proto3" json:"mini_program,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageSendMiniProgramRequest) Reset()         { *m = MessageSendMiniProgramRequest{} }
func (m *MessageSendMiniProgramRequest) String() string { return proto.CompactTextString(m) }
func (*MessageSendMiniProgramRequest) ProtoMessage()    {}
func (*MessageSendMiniProgramRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{18}
}

func (m *MessageSendMiniProgramRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSendMiniProgramRequest.Unmarshal(m, b)
}
func (m *MessageSendMiniProgramRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSendMiniProgramRequest.Marshal(b, m, deterministic)
}
func (m *MessageSendMiniProgramRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSendMiniProgramRequest.Merge(m, src)
}
func (m *MessageSendMiniProgramRequest) XXX_Size() int {
	return xxx_messageInfo_MessageSendMiniProgramRequest.Size(m)
}
func (m *MessageSendMiniProgramRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSendMiniProgramRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSendMiniProgramRequest proto.InternalMessageInfo

func (m *MessageSendMiniProgramRequest) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *MessageSendMiniProgramRequest) GetMiniProgram() string {
	if m != nil {
		return m.MiniProgram
	}
	return ""
}

type MessageSendMiniProgramResponse struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MessageSendMiniProgramResponse) Reset()         { *m = MessageSendMiniProgramResponse{} }
func (m *MessageSendMiniProgramResponse) String() string { return proto.CompactTextString(m) }
func (*MessageSendMiniProgramResponse) ProtoMessage()    {}
func (*MessageSendMiniProgramResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{19}
}

func (m *MessageSendMiniProgramResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSendMiniProgramResponse.Unmarshal(m, b)
}
func (m *MessageSendMiniProgramResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSendMiniProgramResponse.Marshal(b, m, deterministic)
}
func (m *MessageSendMiniProgramResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSendMiniProgramResponse.Merge(m, src)
}
func (m *MessageSendMiniProgramResponse) XXX_Size() int {
	return xxx_messageInfo_MessageSendMiniProgramResponse.Size(m)
}
func (m *MessageSendMiniProgramResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSendMiniProgramResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSendMiniProgramResponse proto.InternalMessageInfo

func (m *MessageSendMiniProgramResponse) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

type MessageSendUrlRequest struct {
	ConversationId       string   `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UrlLink              string   `protobuf:"bytes,2,opt,name=url_link,json=urlLink,proto3" json:"url_link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageSendUrlRequest) Reset()         { *m = MessageSendUrlRequest{} }
func (m *MessageSendUrlRequest) String() string { return proto.CompactTextString(m) }
func (*MessageSendUrlRequest) ProtoMessage()    {}
func (*MessageSendUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{20}
}

func (m *MessageSendUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSendUrlRequest.Unmarshal(m, b)
}
func (m *MessageSendUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSendUrlRequest.Marshal(b, m, deterministic)
}
func (m *MessageSendUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSendUrlRequest.Merge(m, src)
}
func (m *MessageSendUrlRequest) XXX_Size() int {
	return xxx_messageInfo_MessageSendUrlRequest.Size(m)
}
func (m *MessageSendUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSendUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSendUrlRequest proto.InternalMessageInfo

func (m *MessageSendUrlRequest) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *MessageSendUrlRequest) GetUrlLink() string {
	if m != nil {
		return m.UrlLink
	}
	return ""
}

type MessageSendUrlResponse struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MessageSendUrlResponse) Reset()         { *m = MessageSendUrlResponse{} }
func (m *MessageSendUrlResponse) String() string { return proto.CompactTextString(m) }
func (*MessageSendUrlResponse) ProtoMessage()    {}
func (*MessageSendUrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{21}
}

func (m *MessageSendUrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSendUrlResponse.Unmarshal(m, b)
}
func (m *MessageSendUrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSendUrlResponse.Marshal(b, m, deterministic)
}
func (m *MessageSendUrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSendUrlResponse.Merge(m, src)
}
func (m *MessageSendUrlResponse) XXX_Size() int {
	return xxx_messageInfo_MessageSendUrlResponse.Size(m)
}
func (m *MessageSendUrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSendUrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSendUrlResponse proto.InternalMessageInfo

func (m *MessageSendUrlResponse) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

type MessageRecallRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRecallRequest) Reset()         { *m = MessageRecallRequest{} }
func (m *MessageRecallRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRecallRequest) ProtoMessage()    {}
func (*MessageRecallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{22}
}

func (m *MessageRecallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRecallRequest.Unmarshal(m, b)
}
func (m *MessageRecallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRecallRequest.Marshal(b, m, deterministic)
}
func (m *MessageRecallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRecallRequest.Merge(m, src)
}
func (m *MessageRecallRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRecallRequest.Size(m)
}
func (m *MessageRecallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRecallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRecallRequest proto.InternalMessageInfo

func (m *MessageRecallRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessageRecallResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRecallResponse) Reset()         { *m = MessageRecallResponse{} }
func (m *MessageRecallResponse) String() string { return proto.CompactTextString(m) }
func (*MessageRecallResponse) ProtoMessage()    {}
func (*MessageRecallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{23}
}

func (m *MessageRecallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRecallResponse.Unmarshal(m, b)
}
func (m *MessageRecallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRecallResponse.Marshal(b, m, deterministic)
}
func (m *MessageRecallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRecallResponse.Merge(m, src)
}
func (m *MessageRecallResponse) XXX_Size() int {
	return xxx_messageInfo_MessageRecallResponse.Size(m)
}
func (m *MessageRecallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRecallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRecallResponse proto.InternalMessageInfo

func (m *MessageRecallResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterEnum("wechaty.puppet.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("wechaty.puppet.ImageType", ImageType_name, ImageType_value)
	proto.RegisterType((*MessagePayloadRequest)(nil), "wechaty.puppet.MessagePayloadRequest")
	proto.RegisterType((*MessagePayloadResponse)(nil), "wechaty.puppet.MessagePayloadResponse")
	proto.RegisterType((*MessageImageRequest)(nil), "wechaty.puppet.MessageImageRequest")
	proto.RegisterType((*MessageImageResponse)(nil), "wechaty.puppet.MessageImageResponse")
	proto.RegisterType((*MessageContactRequest)(nil), "wechaty.puppet.MessageContactRequest")
	proto.RegisterType((*MessageContactResponse)(nil), "wechaty.puppet.MessageContactResponse")
	proto.RegisterType((*MessageFileRequest)(nil), "wechaty.puppet.MessageFileRequest")
	proto.RegisterType((*MessageFileResponse)(nil), "wechaty.puppet.MessageFileResponse")
	proto.RegisterType((*MessageMiniProgramRequest)(nil), "wechaty.puppet.MessageMiniProgramRequest")
	proto.RegisterType((*MessageMiniProgramResponse)(nil), "wechaty.puppet.MessageMiniProgramResponse")
	proto.RegisterType((*MessageUrlRequest)(nil), "wechaty.puppet.MessageUrlRequest")
	proto.RegisterType((*MessageUrlResponse)(nil), "wechaty.puppet.MessageUrlResponse")
	proto.RegisterType((*MessageSendContactRequest)(nil), "wechaty.puppet.MessageSendContactRequest")
	proto.RegisterType((*MessageSendContactResponse)(nil), "wechaty.puppet.MessageSendContactResponse")
	proto.RegisterType((*MessageSendFileRequest)(nil), "wechaty.puppet.MessageSendFileRequest")
	proto.RegisterType((*MessageSendFileResponse)(nil), "wechaty.puppet.MessageSendFileResponse")
	proto.RegisterType((*MessageSendTextRequest)(nil), "wechaty.puppet.MessageSendTextRequest")
	proto.RegisterType((*MessageSendTextResponse)(nil), "wechaty.puppet.MessageSendTextResponse")
	proto.RegisterType((*MessageSendMiniProgramRequest)(nil), "wechaty.puppet.MessageSendMiniProgramRequest")
	proto.RegisterType((*MessageSendMiniProgramResponse)(nil), "wechaty.puppet.MessageSendMiniProgramResponse")
	proto.RegisterType((*MessageSendUrlRequest)(nil), "wechaty.puppet.MessageSendUrlRequest")
	proto.RegisterType((*MessageSendUrlResponse)(nil), "wechaty.puppet.MessageSendUrlResponse")
	proto.RegisterType((*MessageRecallRequest)(nil), "wechaty.puppet.MessageRecallRequest")
	proto.RegisterType((*MessageRecallResponse)(nil), "wechaty.puppet.MessageRecallResponse")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 933 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xef, 0x72, 0x9b, 0x46,
	0x10, 0xaf, 0x90, 0x6c, 0x4b, 0xab, 0x58, 0x3d, 0x5f, 0xfc, 0x07, 0x39, 0x76, 0xea, 0xaa, 0x9d,
	0x46, 0x93, 0xd6, 0x52, 0x9b, 0x3e, 0x40, 0x87, 0x48, 0xd8, 0xa2, 0x11, 0xa0, 0x41, 0xd8, 0x6d,
	0xda, 0x0f, 0x1a, 0x2c, 0xce, 0x32, 0x63, 0xe0, 0x28, 0x9c, 0x1a, 0xfb, 0x29, 0xfa, 0x0a, 0x7d,
	0xd4, 0x0e, 0x70, 0xc2, 0x20, 0x59, 0x53, 0xc7, 0x9f, 0xe0, 0x76, 0x7f, 0xbb, 0xfb, 0xdb, 0x7f,
	0x77, 0xb0, 0xed, 0x91, 0x28, 0xb2, 0x66, 0xa4, 0x13, 0x84, 0x94, 0x51, 0xdc, 0xf8, 0x44, 0xa6,
	0x37, 0x16, 0xbb, 0xef, 0x04, 0xf3, 0x20, 0x20, 0xec, 0xf0, 0xf5, 0x8c, 0xd2, 0x99, 0x4b, 0xba,
	0x89, 0xf6, 0x6a, 0x7e, 0xdd, 0xfd, 0x14, 0x5a, 0x41, 0x40, 0xc2, 0x28, 0xc5, 0xb7, 0xde, 0xc0,
	0x9e, 0x9a, 0x3a, 0x18, 0x59, 0xf7, 0x2e, 0xb5, 0x6c, 0x83, 0xfc, 0x35, 0x27, 0x11, 0xc3, 0x0d,
	0x10, 0x1c, 0x5b, 0x2c, 0x9d, 0x94, 0xda, 0x35, 0x43, 0x70, 0xec, 0xd6, 0x3f, 0x02, 0xec, 0x2f,
	0x23, 0xa3, 0x80, 0xfa, 0x11, 0x59, 0x86, 0xe2, 0x43, 0xa8, 0x5e, 0x3b, 0x2e, 0xf1, 0x2d, 0x8f,
	0x88, 0x42, 0x22, 0xcd, 0xce, 0x18, 0x43, 0x85, 0x91, 0x3b, 0x26, 0x96, 0x13, 0x79, 0xf2, 0x8f,
	0x8f, 0xa0, 0xc6, 0x1c, 0x8f, 0x44, 0xcc, 0xf2, 0x02, 0xb1, 0x72, 0x52, 0x6a, 0x57, 0x8c, 0x07,
	0x01, 0xee, 0x42, 0x85, 0xdd, 0x07, 0x44, 0xdc, 0x38, 0x29, 0xb5, 0x1b, 0xef, 0x5e, 0x75, 0x8a,
	0x09, 0x76, 0x38, 0x27, 0xf3, 0x3e, 0x20, 0x46, 0x02, 0xc4, 0x07, 0xb0, 0x75, 0x1d, 0x52, 0x6f,
	0xe2, 0xd8, 0xe2, 0x66, 0x12, 0x65, 0x33, 0x3e, 0x2a, 0x76, 0xac, 0x08, 0x69, 0xaa, 0xd8, 0x4a,
	0x15, 0xf1, 0x51, 0xb1, 0xf1, 0x4b, 0xd8, 0x60, 0x34, 0x16, 0x57, 0x39, 0x2b, 0xaa, 0xd8, 0xf8,
	0x2b, 0xa8, 0x7b, 0xc4, 0x67, 0x0e, 0xf5, 0x27, 0x8e, 0x1d, 0x89, 0xb5, 0x93, 0x72, 0xbb, 0x66,
	0x00, 0x17, 0x29, 0x76, 0xd4, 0x32, 0xe1, 0x25, 0x0f, 0xae, 0x78, 0xd6, 0x8c, 0xac, 0x29, 0x1c,
	0x3e, 0xe5, 0xfc, 0x85, 0x84, 0x7f, 0x73, 0x99, 0x7f, 0x62, 0xfb, 0xc0, 0xbe, 0xf5, 0x23, 0xec,
	0x16, 0xbd, 0xf2, 0x22, 0x8b, 0xb0, 0x15, 0x17, 0xf1, 0x8a, 0xde, 0x71, 0xdf, 0x8b, 0x63, 0xae,
	0x85, 0x3d, 0xea, 0x33, 0x6b, 0xca, 0xd6, 0xb5, 0xb0, 0x9d, 0x75, 0x30, 0x03, 0x3e, 0xde, 0xc1,
	0xd6, 0xb7, 0x80, 0x39, 0xf2, 0xcc, 0x71, 0xd7, 0x65, 0xd6, 0xea, 0x66, 0x05, 0x48, 0x51, 0xff,
	0xcb, 0xf4, 0x7b, 0x68, 0x72, 0x03, 0xd5, 0xf1, 0x9d, 0x51, 0x48, 0x67, 0xa1, 0xe5, 0xad, 0xf3,
	0xfe, 0x0b, 0x1c, 0x3e, 0x06, 0xe6, 0x41, 0xbe, 0x86, 0x17, 0x9e, 0xe3, 0x3b, 0x93, 0x20, 0x95,
	0x73, 0xbb, 0xba, 0xf7, 0x00, 0x6d, 0x7d, 0x03, 0x3b, 0xdc, 0xc1, 0x45, 0xe8, 0xae, 0xcf, 0x01,
	0xe7, 0x41, 0xdc, 0x7b, 0x13, 0xaa, 0xf3, 0xd0, 0x9d, 0xb8, 0x8e, 0x7f, 0xbb, 0xc8, 0x61, 0x1e,
	0xba, 0x43, 0xc7, 0xbf, 0x6d, 0x4d, 0xb3, 0x1c, 0xc6, 0xc4, 0xb7, 0x97, 0x2a, 0xfe, 0x06, 0xbe,
	0x9c, 0x52, 0xff, 0x6f, 0x12, 0x46, 0x16, 0x1f, 0x1c, 0x6e, 0xde, 0xc8, 0x8b, 0x15, 0x1b, 0x1f,
	0x03, 0x4c, 0x53, 0xd3, 0x18, 0x93, 0x2e, 0x49, 0x8d, 0x4b, 0x14, 0xbb, 0xf5, 0x6b, 0x96, 0x7b,
	0x21, 0x08, 0x67, 0xf7, 0x43, 0x96, 0x43, 0xfd, 0xdd, 0x51, 0x27, 0x5d, 0xf0, 0xce, 0x62, 0xc1,
	0x3b, 0x63, 0x16, 0x3a, 0xfe, 0xec, 0xd2, 0x72, 0xe7, 0x24, 0xc9, 0xf0, 0xcf, 0xac, 0xeb, 0xb1,
	0xaf, 0x7c, 0x3f, 0x9f, 0xcc, 0x36, 0xd7, 0x51, 0xa1, 0xd8, 0xd1, 0x73, 0x38, 0x58, 0x71, 0xfe,
	0x2c, 0x96, 0x77, 0x05, 0x96, 0x26, 0xb9, 0xfb, 0xfc, 0x9a, 0x2e, 0xae, 0x16, 0x21, 0x77, 0xb5,
	0xc4, 0x63, 0x42, 0x7c, 0x46, 0x7d, 0xcb, 0x4d, 0xb6, 0xb8, 0x9c, 0x6c, 0x71, 0x7d, 0x21, 0x8b,
	0xd7, 0xb8, 0x98, 0x42, 0x1a, 0xf9, 0x59, 0x29, 0xdc, 0xc2, 0x71, 0xce, 0xd1, 0x23, 0x13, 0xfe,
	0xe4, 0x4c, 0x96, 0x87, 0x5b, 0x58, 0x1d, 0x6e, 0x0d, 0x5e, 0xaf, 0x0b, 0xf6, 0xcc, 0x29, 0xd9,
	0xcb, 0xf9, 0xcb, 0x2d, 0xcc, 0x93, 0x49, 0xe7, 0x77, 0x46, 0x28, 0xee, 0xcc, 0x59, 0xa1, 0xb9,
	0xf9, 0x45, 0xfb, 0x3c, 0x92, 0xdf, 0x65, 0x77, 0xa3, 0x41, 0xa6, 0x96, 0xbb, 0x76, 0xa9, 0x7f,
	0xca, 0x92, 0x59, 0xe0, 0x1e, 0xae, 0xa6, 0x68, 0x3e, 0x9d, 0x92, 0x28, 0x4a, 0xd0, 0x55, 0x63,
	0x71, 0x7c, 0xfb, 0x6f, 0x19, 0xea, 0xb9, 0xa7, 0x04, 0x1f, 0x81, 0xa8, 0xca, 0xe3, 0xb1, 0x74,
	0x2e, 0x4f, 0xcc, 0x8f, 0x23, 0x79, 0x72, 0xa1, 0x8d, 0x47, 0x72, 0x4f, 0x39, 0x53, 0xe4, 0x3e,
	0xfa, 0x02, 0xbf, 0x82, 0x83, 0x82, 0x56, 0x32, 0x4d, 0xa9, 0x37, 0x50, 0x65, 0xcd, 0x44, 0x25,
	0xbc, 0x0f, 0xb8, 0xa8, 0xbc, 0xe8, 0x2b, 0x3a, 0x12, 0xb0, 0x08, 0xbb, 0x05, 0x79, 0x4f, 0xd7,
	0x4c, 0xa9, 0x67, 0xa2, 0x32, 0x6e, 0xc2, 0x5e, 0x41, 0x23, 0xab, 0xba, 0xa9, 0xf4, 0x74, 0x0d,
	0x55, 0x56, 0x9c, 0x29, 0xaa, 0x74, 0x2e, 0xa3, 0x0d, 0xbc, 0x07, 0x3b, 0x05, 0xb9, 0x29, 0xff,
	0x6e, 0xa2, 0xcd, 0x15, 0xf8, 0xa5, 0xd2, 0x97, 0x75, 0xb4, 0x85, 0x8f, 0xa1, 0x59, 0x8c, 0x3d,
	0x90, 0xcc, 0xc9, 0x40, 0x19, 0x9b, 0xba, 0xf1, 0x11, 0x55, 0x57, 0x08, 0x0c, 0xf5, 0x9e, 0x64,
	0x2a, 0xba, 0x86, 0x6a, 0x2b, 0x96, 0xaa, 0xa2, 0x29, 0x93, 0x91, 0xa1, 0x9f, 0x1b, 0x92, 0x8a,
	0x60, 0xc5, 0xd2, 0x34, 0x24, 0x6d, 0x7c, 0x26, 0x1b, 0xa8, 0xbe, 0x62, 0x69, 0xc8, 0xfd, 0x89,
	0xac, 0x5d, 0xca, 0x43, 0x7d, 0x24, 0xa3, 0x17, 0x2b, 0x96, 0x86, 0xdc, 0x93, 0x86, 0x43, 0xb9,
	0x8f, 0xb6, 0xf1, 0x2e, 0xa0, 0x62, 0xf1, 0x8d, 0x21, 0x6a, 0xbc, 0x75, 0xa1, 0x96, 0x3d, 0x96,
	0xf8, 0x10, 0xf6, 0x93, 0x52, 0x3c, 0xd6, 0x1d, 0x11, 0x76, 0x73, 0x3a, 0x73, 0x70, 0xa1, 0xbe,
	0xd7, 0x24, 0x65, 0x88, 0x4a, 0x78, 0x07, 0xb6, 0x73, 0x9a, 0x41, 0x1f, 0x09, 0x71, 0xc5, 0x72,
	0x22, 0xc9, 0x30, 0x7f, 0xd3, 0x8d, 0x0f, 0xa8, 0xfc, 0x5e, 0xfd, 0xe3, 0xc3, 0xcc, 0x61, 0x37,
	0xf3, 0xab, 0xce, 0x94, 0x7a, 0x5d, 0xfe, 0x68, 0x77, 0x67, 0xf4, 0x74, 0xf1, 0xcb, 0xbf, 0xa7,
	0xe9, 0x3b, 0x7e, 0x7a, 0x43, 0x23, 0xe6, 0x90, 0xee, 0x8c, 0xf8, 0x24, 0xb4, 0x18, 0xc9, 0x2c,
	0x52, 0xf5, 0xd5, 0x66, 0x32, 0xd4, 0x3f, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0xdb, 0xe5, 0x22,
	0x0c, 0xaf, 0x09, 0x00, 0x00,
}
