// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room.proto

package puppet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoomListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomListRequest) Reset()         { *m = RoomListRequest{} }
func (m *RoomListRequest) String() string { return proto.CompactTextString(m) }
func (*RoomListRequest) ProtoMessage()    {}
func (*RoomListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{0}
}

func (m *RoomListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomListRequest.Unmarshal(m, b)
}
func (m *RoomListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomListRequest.Marshal(b, m, deterministic)
}
func (m *RoomListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomListRequest.Merge(m, src)
}
func (m *RoomListRequest) XXX_Size() int {
	return xxx_messageInfo_RoomListRequest.Size(m)
}
func (m *RoomListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomListRequest proto.InternalMessageInfo

type RoomListResponse struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomListResponse) Reset()         { *m = RoomListResponse{} }
func (m *RoomListResponse) String() string { return proto.CompactTextString(m) }
func (*RoomListResponse) ProtoMessage()    {}
func (*RoomListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{1}
}

func (m *RoomListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomListResponse.Unmarshal(m, b)
}
func (m *RoomListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomListResponse.Marshal(b, m, deterministic)
}
func (m *RoomListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomListResponse.Merge(m, src)
}
func (m *RoomListResponse) XXX_Size() int {
	return xxx_messageInfo_RoomListResponse.Size(m)
}
func (m *RoomListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomListResponse proto.InternalMessageInfo

func (m *RoomListResponse) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type RoomPayloadRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomPayloadRequest) Reset()         { *m = RoomPayloadRequest{} }
func (m *RoomPayloadRequest) String() string { return proto.CompactTextString(m) }
func (*RoomPayloadRequest) ProtoMessage()    {}
func (*RoomPayloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{2}
}

func (m *RoomPayloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomPayloadRequest.Unmarshal(m, b)
}
func (m *RoomPayloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomPayloadRequest.Marshal(b, m, deterministic)
}
func (m *RoomPayloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomPayloadRequest.Merge(m, src)
}
func (m *RoomPayloadRequest) XXX_Size() int {
	return xxx_messageInfo_RoomPayloadRequest.Size(m)
}
func (m *RoomPayloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomPayloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomPayloadRequest proto.InternalMessageInfo

func (m *RoomPayloadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RoomPayloadResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	OwnerId              string   `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	AdminIds             []string `protobuf:"bytes,5,rep,name=admin_ids,json=adminIds,proto3" json:"admin_ids,omitempty"`
	MemberIds            []string `protobuf:"bytes,6,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomPayloadResponse) Reset()         { *m = RoomPayloadResponse{} }
func (m *RoomPayloadResponse) String() string { return proto.CompactTextString(m) }
func (*RoomPayloadResponse) ProtoMessage()    {}
func (*RoomPayloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{3}
}

func (m *RoomPayloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomPayloadResponse.Unmarshal(m, b)
}
func (m *RoomPayloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomPayloadResponse.Marshal(b, m, deterministic)
}
func (m *RoomPayloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomPayloadResponse.Merge(m, src)
}
func (m *RoomPayloadResponse) XXX_Size() int {
	return xxx_messageInfo_RoomPayloadResponse.Size(m)
}
func (m *RoomPayloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomPayloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomPayloadResponse proto.InternalMessageInfo

func (m *RoomPayloadResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RoomPayloadResponse) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *RoomPayloadResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *RoomPayloadResponse) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *RoomPayloadResponse) GetAdminIds() []string {
	if m != nil {
		return m.AdminIds
	}
	return nil
}

func (m *RoomPayloadResponse) GetMemberIds() []string {
	if m != nil {
		return m.MemberIds
	}
	return nil
}

type RoomAddRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContactId            string   `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomAddRequest) Reset()         { *m = RoomAddRequest{} }
func (m *RoomAddRequest) String() string { return proto.CompactTextString(m) }
func (*RoomAddRequest) ProtoMessage()    {}
func (*RoomAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{4}
}

func (m *RoomAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomAddRequest.Unmarshal(m, b)
}
func (m *RoomAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomAddRequest.Marshal(b, m, deterministic)
}
func (m *RoomAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomAddRequest.Merge(m, src)
}
func (m *RoomAddRequest) XXX_Size() int {
	return xxx_messageInfo_RoomAddRequest.Size(m)
}
func (m *RoomAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomAddRequest proto.InternalMessageInfo

func (m *RoomAddRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RoomAddRequest) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

type RoomAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomAddResponse) Reset()         { *m = RoomAddResponse{} }
func (m *RoomAddResponse) String() string { return proto.CompactTextString(m) }
func (*RoomAddResponse) ProtoMessage()    {}
func (*RoomAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{5}
}

func (m *RoomAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomAddResponse.Unmarshal(m, b)
}
func (m *RoomAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomAddResponse.Marshal(b, m, deterministic)
}
func (m *RoomAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomAddResponse.Merge(m, src)
}
func (m *RoomAddResponse) XXX_Size() int {
	return xxx_messageInfo_RoomAddResponse.Size(m)
}
func (m *RoomAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomAddResponse proto.InternalMessageInfo

type RoomAvatarRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomAvatarRequest) Reset()         { *m = RoomAvatarRequest{} }
func (m *RoomAvatarRequest) String() string { return proto.CompactTextString(m) }
func (*RoomAvatarRequest) ProtoMessage()    {}
func (*RoomAvatarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{6}
}

func (m *RoomAvatarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomAvatarRequest.Unmarshal(m, b)
}
func (m *RoomAvatarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomAvatarRequest.Marshal(b, m, deterministic)
}
func (m *RoomAvatarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomAvatarRequest.Merge(m, src)
}
func (m *RoomAvatarRequest) XXX_Size() int {
	return xxx_messageInfo_RoomAvatarRequest.Size(m)
}
func (m *RoomAvatarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomAvatarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomAvatarRequest proto.InternalMessageInfo

func (m *RoomAvatarRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RoomAvatarResponse struct {
	Filebox              string   `protobuf:"bytes,1,opt,name=filebox,proto3" json:"filebox,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomAvatarResponse) Reset()         { *m = RoomAvatarResponse{} }
func (m *RoomAvatarResponse) String() string { return proto.CompactTextString(m) }
func (*RoomAvatarResponse) ProtoMessage()    {}
func (*RoomAvatarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{7}
}

func (m *RoomAvatarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomAvatarResponse.Unmarshal(m, b)
}
func (m *RoomAvatarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomAvatarResponse.Marshal(b, m, deterministic)
}
func (m *RoomAvatarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomAvatarResponse.Merge(m, src)
}
func (m *RoomAvatarResponse) XXX_Size() int {
	return xxx_messageInfo_RoomAvatarResponse.Size(m)
}
func (m *RoomAvatarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomAvatarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomAvatarResponse proto.InternalMessageInfo

func (m *RoomAvatarResponse) GetFilebox() string {
	if m != nil {
		return m.Filebox
	}
	return ""
}

type RoomCreateRequest struct {
	ContactIds           []string `protobuf:"bytes,1,rep,name=contact_ids,json=contactIds,proto3" json:"contact_ids,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomCreateRequest) Reset()         { *m = RoomCreateRequest{} }
func (m *RoomCreateRequest) String() string { return proto.CompactTextString(m) }
func (*RoomCreateRequest) ProtoMessage()    {}
func (*RoomCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{8}
}

func (m *RoomCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomCreateRequest.Unmarshal(m, b)
}
func (m *RoomCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomCreateRequest.Marshal(b, m, deterministic)
}
func (m *RoomCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomCreateRequest.Merge(m, src)
}
func (m *RoomCreateRequest) XXX_Size() int {
	return xxx_messageInfo_RoomCreateRequest.Size(m)
}
func (m *RoomCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomCreateRequest proto.InternalMessageInfo

func (m *RoomCreateRequest) GetContactIds() []string {
	if m != nil {
		return m.ContactIds
	}
	return nil
}

func (m *RoomCreateRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type RoomCreateResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomCreateResponse) Reset()         { *m = RoomCreateResponse{} }
func (m *RoomCreateResponse) String() string { return proto.CompactTextString(m) }
func (*RoomCreateResponse) ProtoMessage()    {}
func (*RoomCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{9}
}

func (m *RoomCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomCreateResponse.Unmarshal(m, b)
}
func (m *RoomCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomCreateResponse.Marshal(b, m, deterministic)
}
func (m *RoomCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomCreateResponse.Merge(m, src)
}
func (m *RoomCreateResponse) XXX_Size() int {
	return xxx_messageInfo_RoomCreateResponse.Size(m)
}
func (m *RoomCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomCreateResponse proto.InternalMessageInfo

func (m *RoomCreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RoomDelRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContactId            string   `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomDelRequest) Reset()         { *m = RoomDelRequest{} }
func (m *RoomDelRequest) String() string { return proto.CompactTextString(m) }
func (*RoomDelRequest) ProtoMessage()    {}
func (*RoomDelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{10}
}

func (m *RoomDelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomDelRequest.Unmarshal(m, b)
}
func (m *RoomDelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomDelRequest.Marshal(b, m, deterministic)
}
func (m *RoomDelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomDelRequest.Merge(m, src)
}
func (m *RoomDelRequest) XXX_Size() int {
	return xxx_messageInfo_RoomDelRequest.Size(m)
}
func (m *RoomDelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomDelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomDelRequest proto.InternalMessageInfo

func (m *RoomDelRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RoomDelRequest) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

type RoomDelResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomDelResponse) Reset()         { *m = RoomDelResponse{} }
func (m *RoomDelResponse) String() string { return proto.CompactTextString(m) }
func (*RoomDelResponse) ProtoMessage()    {}
func (*RoomDelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{11}
}

func (m *RoomDelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomDelResponse.Unmarshal(m, b)
}
func (m *RoomDelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomDelResponse.Marshal(b, m, deterministic)
}
func (m *RoomDelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomDelResponse.Merge(m, src)
}
func (m *RoomDelResponse) XXX_Size() int {
	return xxx_messageInfo_RoomDelResponse.Size(m)
}
func (m *RoomDelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomDelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomDelResponse proto.InternalMessageInfo

type RoomQuitRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomQuitRequest) Reset()         { *m = RoomQuitRequest{} }
func (m *RoomQuitRequest) String() string { return proto.CompactTextString(m) }
func (*RoomQuitRequest) ProtoMessage()    {}
func (*RoomQuitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{12}
}

func (m *RoomQuitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomQuitRequest.Unmarshal(m, b)
}
func (m *RoomQuitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomQuitRequest.Marshal(b, m, deterministic)
}
func (m *RoomQuitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomQuitRequest.Merge(m, src)
}
func (m *RoomQuitRequest) XXX_Size() int {
	return xxx_messageInfo_RoomQuitRequest.Size(m)
}
func (m *RoomQuitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomQuitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomQuitRequest proto.InternalMessageInfo

func (m *RoomQuitRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RoomQuitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomQuitResponse) Reset()         { *m = RoomQuitResponse{} }
func (m *RoomQuitResponse) String() string { return proto.CompactTextString(m) }
func (*RoomQuitResponse) ProtoMessage()    {}
func (*RoomQuitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{13}
}

func (m *RoomQuitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomQuitResponse.Unmarshal(m, b)
}
func (m *RoomQuitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomQuitResponse.Marshal(b, m, deterministic)
}
func (m *RoomQuitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomQuitResponse.Merge(m, src)
}
func (m *RoomQuitResponse) XXX_Size() int {
	return xxx_messageInfo_RoomQuitResponse.Size(m)
}
func (m *RoomQuitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomQuitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomQuitResponse proto.InternalMessageInfo

type RoomTopicRequest struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic                *wrappers.StringValue `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RoomTopicRequest) Reset()         { *m = RoomTopicRequest{} }
func (m *RoomTopicRequest) String() string { return proto.CompactTextString(m) }
func (*RoomTopicRequest) ProtoMessage()    {}
func (*RoomTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{14}
}

func (m *RoomTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomTopicRequest.Unmarshal(m, b)
}
func (m *RoomTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomTopicRequest.Marshal(b, m, deterministic)
}
func (m *RoomTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomTopicRequest.Merge(m, src)
}
func (m *RoomTopicRequest) XXX_Size() int {
	return xxx_messageInfo_RoomTopicRequest.Size(m)
}
func (m *RoomTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomTopicRequest proto.InternalMessageInfo

func (m *RoomTopicRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RoomTopicRequest) GetTopic() *wrappers.StringValue {
	if m != nil {
		return m.Topic
	}
	return nil
}

type RoomTopicResponse struct {
	Topic                *wrappers.StringValue `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RoomTopicResponse) Reset()         { *m = RoomTopicResponse{} }
func (m *RoomTopicResponse) String() string { return proto.CompactTextString(m) }
func (*RoomTopicResponse) ProtoMessage()    {}
func (*RoomTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{15}
}

func (m *RoomTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomTopicResponse.Unmarshal(m, b)
}
func (m *RoomTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomTopicResponse.Marshal(b, m, deterministic)
}
func (m *RoomTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomTopicResponse.Merge(m, src)
}
func (m *RoomTopicResponse) XXX_Size() int {
	return xxx_messageInfo_RoomTopicResponse.Size(m)
}
func (m *RoomTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomTopicResponse proto.InternalMessageInfo

func (m *RoomTopicResponse) GetTopic() *wrappers.StringValue {
	if m != nil {
		return m.Topic
	}
	return nil
}

type RoomQRCodeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomQRCodeRequest) Reset()         { *m = RoomQRCodeRequest{} }
func (m *RoomQRCodeRequest) String() string { return proto.CompactTextString(m) }
func (*RoomQRCodeRequest) ProtoMessage()    {}
func (*RoomQRCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{16}
}

func (m *RoomQRCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomQRCodeRequest.Unmarshal(m, b)
}
func (m *RoomQRCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomQRCodeRequest.Marshal(b, m, deterministic)
}
func (m *RoomQRCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomQRCodeRequest.Merge(m, src)
}
func (m *RoomQRCodeRequest) XXX_Size() int {
	return xxx_messageInfo_RoomQRCodeRequest.Size(m)
}
func (m *RoomQRCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomQRCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomQRCodeRequest proto.InternalMessageInfo

func (m *RoomQRCodeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RoomQRCodeResponse struct {
	Qrcode               string   `protobuf:"bytes,1,opt,name=qrcode,proto3" json:"qrcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomQRCodeResponse) Reset()         { *m = RoomQRCodeResponse{} }
func (m *RoomQRCodeResponse) String() string { return proto.CompactTextString(m) }
func (*RoomQRCodeResponse) ProtoMessage()    {}
func (*RoomQRCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{17}
}

func (m *RoomQRCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomQRCodeResponse.Unmarshal(m, b)
}
func (m *RoomQRCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomQRCodeResponse.Marshal(b, m, deterministic)
}
func (m *RoomQRCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomQRCodeResponse.Merge(m, src)
}
func (m *RoomQRCodeResponse) XXX_Size() int {
	return xxx_messageInfo_RoomQRCodeResponse.Size(m)
}
func (m *RoomQRCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomQRCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomQRCodeResponse proto.InternalMessageInfo

func (m *RoomQRCodeResponse) GetQrcode() string {
	if m != nil {
		return m.Qrcode
	}
	return ""
}

type RoomAnnounceRequest struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RoomAnnounceRequest) Reset()         { *m = RoomAnnounceRequest{} }
func (m *RoomAnnounceRequest) String() string { return proto.CompactTextString(m) }
func (*RoomAnnounceRequest) ProtoMessage()    {}
func (*RoomAnnounceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{18}
}

func (m *RoomAnnounceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomAnnounceRequest.Unmarshal(m, b)
}
func (m *RoomAnnounceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomAnnounceRequest.Marshal(b, m, deterministic)
}
func (m *RoomAnnounceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomAnnounceRequest.Merge(m, src)
}
func (m *RoomAnnounceRequest) XXX_Size() int {
	return xxx_messageInfo_RoomAnnounceRequest.Size(m)
}
func (m *RoomAnnounceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomAnnounceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomAnnounceRequest proto.InternalMessageInfo

func (m *RoomAnnounceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RoomAnnounceRequest) GetText() *wrappers.StringValue {
	if m != nil {
		return m.Text
	}
	return nil
}

type RoomAnnounceResponse struct {
	Text                 *wrappers.StringValue `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RoomAnnounceResponse) Reset()         { *m = RoomAnnounceResponse{} }
func (m *RoomAnnounceResponse) String() string { return proto.CompactTextString(m) }
func (*RoomAnnounceResponse) ProtoMessage()    {}
func (*RoomAnnounceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{19}
}

func (m *RoomAnnounceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomAnnounceResponse.Unmarshal(m, b)
}
func (m *RoomAnnounceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomAnnounceResponse.Marshal(b, m, deterministic)
}
func (m *RoomAnnounceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomAnnounceResponse.Merge(m, src)
}
func (m *RoomAnnounceResponse) XXX_Size() int {
	return xxx_messageInfo_RoomAnnounceResponse.Size(m)
}
func (m *RoomAnnounceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomAnnounceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomAnnounceResponse proto.InternalMessageInfo

func (m *RoomAnnounceResponse) GetText() *wrappers.StringValue {
	if m != nil {
		return m.Text
	}
	return nil
}

func init() {
	proto.RegisterType((*RoomListRequest)(nil), "wechaty.puppet.RoomListRequest")
	proto.RegisterType((*RoomListResponse)(nil), "wechaty.puppet.RoomListResponse")
	proto.RegisterType((*RoomPayloadRequest)(nil), "wechaty.puppet.RoomPayloadRequest")
	proto.RegisterType((*RoomPayloadResponse)(nil), "wechaty.puppet.RoomPayloadResponse")
	proto.RegisterType((*RoomAddRequest)(nil), "wechaty.puppet.RoomAddRequest")
	proto.RegisterType((*RoomAddResponse)(nil), "wechaty.puppet.RoomAddResponse")
	proto.RegisterType((*RoomAvatarRequest)(nil), "wechaty.puppet.RoomAvatarRequest")
	proto.RegisterType((*RoomAvatarResponse)(nil), "wechaty.puppet.RoomAvatarResponse")
	proto.RegisterType((*RoomCreateRequest)(nil), "wechaty.puppet.RoomCreateRequest")
	proto.RegisterType((*RoomCreateResponse)(nil), "wechaty.puppet.RoomCreateResponse")
	proto.RegisterType((*RoomDelRequest)(nil), "wechaty.puppet.RoomDelRequest")
	proto.RegisterType((*RoomDelResponse)(nil), "wechaty.puppet.RoomDelResponse")
	proto.RegisterType((*RoomQuitRequest)(nil), "wechaty.puppet.RoomQuitRequest")
	proto.RegisterType((*RoomQuitResponse)(nil), "wechaty.puppet.RoomQuitResponse")
	proto.RegisterType((*RoomTopicRequest)(nil), "wechaty.puppet.RoomTopicRequest")
	proto.RegisterType((*RoomTopicResponse)(nil), "wechaty.puppet.RoomTopicResponse")
	proto.RegisterType((*RoomQRCodeRequest)(nil), "wechaty.puppet.RoomQRCodeRequest")
	proto.RegisterType((*RoomQRCodeResponse)(nil), "wechaty.puppet.RoomQRCodeResponse")
	proto.RegisterType((*RoomAnnounceRequest)(nil), "wechaty.puppet.RoomAnnounceRequest")
	proto.RegisterType((*RoomAnnounceResponse)(nil), "wechaty.puppet.RoomAnnounceResponse")
}

func init() { proto.RegisterFile("room.proto", fileDescriptor_c5fd27dd97284ef4) }

var fileDescriptor_c5fd27dd97284ef4 = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0xda, 0xad, 0x5b, 0xef, 0xa4, 0xb2, 0x99, 0x69, 0x0a, 0xdf, 0x23, 0xec, 0x61, 0x0f,
	0x34, 0x45, 0xe3, 0x07, 0xa0, 0x31, 0x24, 0x28, 0x1f, 0x12, 0x2b, 0x68, 0x48, 0xbc, 0x4c, 0x6e,
	0x7c, 0x97, 0x5a, 0x6a, 0x72, 0x33, 0xdb, 0xa1, 0xdb, 0x5f, 0xe2, 0x57, 0xa2, 0xf8, 0xa3, 0x63,
	0x68, 0x91, 0x2a, 0xf1, 0xd4, 0xdc, 0xe3, 0xe3, 0xe3, 0x73, 0xcf, 0xad, 0x0d, 0xa0, 0x88, 0x8a,
	0xb4, 0x52, 0x64, 0x88, 0x0d, 0x16, 0x98, 0xcd, 0xb8, 0xb9, 0x4e, 0xab, 0xba, 0xaa, 0xd0, 0x3c,
	0x7c, 0x9a, 0x13, 0xe5, 0x73, 0x1c, 0xd9, 0xd5, 0x69, 0x7d, 0x31, 0x5a, 0x28, 0x5e, 0x55, 0xa8,
	0xb4, 0xe3, 0x27, 0x3b, 0x70, 0x6f, 0x42, 0x54, 0x7c, 0x96, 0xda, 0x4c, 0xf0, 0xb2, 0x46, 0x6d,
	0x92, 0x03, 0xd8, 0xbe, 0x81, 0x74, 0x45, 0xa5, 0x46, 0xb6, 0x0d, 0x5d, 0x29, 0x74, 0x1c, 0xed,
	0x77, 0x0f, 0xfb, 0x93, 0xe6, 0x33, 0x39, 0x00, 0xd6, 0xb0, 0xbe, 0xf2, 0xeb, 0x39, 0x71, 0xe1,
	0xf7, 0xb2, 0x01, 0x74, 0xa4, 0x88, 0xa3, 0xfd, 0xe8, 0xb0, 0x3f, 0xe9, 0x48, 0x91, 0xfc, 0x8e,
	0xe0, 0xfe, 0x2d, 0x9a, 0xd7, 0xfb, 0x87, 0xc7, 0x76, 0x61, 0xdd, 0x50, 0x25, 0xb3, 0xb8, 0x63,
	0x21, 0x57, 0xb0, 0x3d, 0xe8, 0xf1, 0x5f, 0xdc, 0x70, 0x15, 0x77, 0x2d, 0xec, 0x2b, 0xf6, 0x00,
	0x36, 0x69, 0x51, 0xa2, 0x3a, 0x97, 0x22, 0x5e, 0xb3, 0x2b, 0x1b, 0xb6, 0x1e, 0x0b, 0xf6, 0x08,
	0xfa, 0x5c, 0x14, 0xb2, 0x3c, 0x6f, 0xec, 0xae, 0x5b, 0xbb, 0x9b, 0x16, 0x18, 0x0b, 0xcd, 0x9e,
	0x00, 0x14, 0x58, 0x4c, 0xed, 0x46, 0x1d, 0xf7, 0xec, 0x6a, 0xdf, 0x21, 0x63, 0xa1, 0x93, 0x37,
	0x30, 0x68, 0xbc, 0x1e, 0x8b, 0xb6, 0x76, 0x1a, 0x81, 0x8c, 0x4a, 0xc3, 0x33, 0xd3, 0x1c, 0xed,
	0xbc, 0xf6, 0x3d, 0x32, 0x16, 0x21, 0x4c, 0x2b, 0xe0, 0x1a, 0x4d, 0x5e, 0xc0, 0x8e, 0x85, 0xac,
	0xf1, 0xb6, 0x94, 0x52, 0x97, 0x65, 0x20, 0xf9, 0x8c, 0x62, 0xd8, 0xb8, 0x90, 0x73, 0x9c, 0xd2,
	0x95, 0xa7, 0x86, 0x32, 0xf9, 0xe8, 0x44, 0x4f, 0x14, 0x72, 0x83, 0x41, 0xf4, 0x19, 0x6c, 0xdd,
	0x78, 0x0b, 0xa3, 0x82, 0xa5, 0x39, 0x7d, 0x77, 0xc6, 0x61, 0x8e, 0x41, 0xeb, 0xee, 0xf9, 0x84,
	0x68, 0xde, 0xe1, 0xfc, 0xff, 0xa2, 0xb1, 0x02, 0x3e, 0x9a, 0xe7, 0x0e, 0x3a, 0xad, 0xa5, 0x69,
	0x0b, 0x86, 0xb9, 0xbf, 0xa2, 0xa3, 0xf8, 0x6d, 0x67, 0x0e, 0xfb, 0xde, 0xb8, 0x6f, 0x33, 0x73,
	0xf4, 0x77, 0xab, 0x5b, 0x47, 0x8f, 0x53, 0x77, 0x0b, 0xd2, 0x70, 0x0b, 0xd2, 0x6f, 0x46, 0xc9,
	0x32, 0x3f, 0xe3, 0xf3, 0x1a, 0x43, 0x10, 0xef, 0x5d, 0xa8, 0x5e, 0xd7, 0xe7, 0xb0, 0x14, 0x8a,
	0x56, 0x17, 0xf2, 0x23, 0x3f, 0x9d, 0x9c, 0x90, 0xc0, 0xb6, 0xce, 0x5e, 0xba, 0xd8, 0x03, 0xc9,
	0x1f, 0xb7, 0x07, 0xbd, 0x4b, 0x95, 0x91, 0x40, 0xcf, 0xf4, 0x55, 0xf2, 0xc3, 0xdd, 0xa2, 0xe3,
	0xb2, 0xa4, 0xba, 0xcc, 0xda, 0x44, 0xd9, 0x2b, 0x58, 0x33, 0x78, 0x65, 0x56, 0xea, 0xda, 0x32,
	0x93, 0x0f, 0xb0, 0x7b, 0x5b, 0xd8, 0x1b, 0x09, 0x4a, 0xd1, 0xaa, 0x4a, 0x6f, 0xbf, 0xfc, 0xfc,
	0x94, 0x4b, 0x33, 0xab, 0xa7, 0x69, 0x46, 0xc5, 0xc8, 0xbf, 0x42, 0xa3, 0x9c, 0x86, 0xe1, 0xd3,
	0xff, 0x0e, 0xdd, 0xc3, 0x34, 0x9c, 0x91, 0x36, 0x12, 0x47, 0x39, 0x96, 0xa8, 0xb8, 0xc1, 0xe5,
	0x0e, 0xb7, 0x3c, 0xed, 0xd9, 0xa3, 0x5e, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x72, 0x9d, 0x32,
	0x76, 0xdc, 0x04, 0x00, 0x00,
}
