// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room_invitation.proto

package puppet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoomInvitationPayloadRequest struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload              *wrappers.StringValue `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RoomInvitationPayloadRequest) Reset()         { *m = RoomInvitationPayloadRequest{} }
func (m *RoomInvitationPayloadRequest) String() string { return proto.CompactTextString(m) }
func (*RoomInvitationPayloadRequest) ProtoMessage()    {}
func (*RoomInvitationPayloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b96d9038b90c638, []int{0}
}

func (m *RoomInvitationPayloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInvitationPayloadRequest.Unmarshal(m, b)
}
func (m *RoomInvitationPayloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInvitationPayloadRequest.Marshal(b, m, deterministic)
}
func (m *RoomInvitationPayloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInvitationPayloadRequest.Merge(m, src)
}
func (m *RoomInvitationPayloadRequest) XXX_Size() int {
	return xxx_messageInfo_RoomInvitationPayloadRequest.Size(m)
}
func (m *RoomInvitationPayloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInvitationPayloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInvitationPayloadRequest proto.InternalMessageInfo

func (m *RoomInvitationPayloadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RoomInvitationPayloadRequest) GetPayload() *wrappers.StringValue {
	if m != nil {
		return m.Payload
	}
	return nil
}

type RoomInvitationPayloadResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InviterId            string   `protobuf:"bytes,2,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	Topic                string   `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	MemberCount          uint32   `protobuf:"varint,4,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	MemberIds            []string `protobuf:"bytes,5,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	Timestamp            uint64   `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Avatar               string   `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Invitation           string   `protobuf:"bytes,8,opt,name=invitation,proto3" json:"invitation,omitempty"`
	ReceiverId           string   `protobuf:"bytes,9,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInvitationPayloadResponse) Reset()         { *m = RoomInvitationPayloadResponse{} }
func (m *RoomInvitationPayloadResponse) String() string { return proto.CompactTextString(m) }
func (*RoomInvitationPayloadResponse) ProtoMessage()    {}
func (*RoomInvitationPayloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b96d9038b90c638, []int{1}
}

func (m *RoomInvitationPayloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInvitationPayloadResponse.Unmarshal(m, b)
}
func (m *RoomInvitationPayloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInvitationPayloadResponse.Marshal(b, m, deterministic)
}
func (m *RoomInvitationPayloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInvitationPayloadResponse.Merge(m, src)
}
func (m *RoomInvitationPayloadResponse) XXX_Size() int {
	return xxx_messageInfo_RoomInvitationPayloadResponse.Size(m)
}
func (m *RoomInvitationPayloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInvitationPayloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInvitationPayloadResponse proto.InternalMessageInfo

func (m *RoomInvitationPayloadResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RoomInvitationPayloadResponse) GetInviterId() string {
	if m != nil {
		return m.InviterId
	}
	return ""
}

func (m *RoomInvitationPayloadResponse) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *RoomInvitationPayloadResponse) GetMemberCount() uint32 {
	if m != nil {
		return m.MemberCount
	}
	return 0
}

func (m *RoomInvitationPayloadResponse) GetMemberIds() []string {
	if m != nil {
		return m.MemberIds
	}
	return nil
}

func (m *RoomInvitationPayloadResponse) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RoomInvitationPayloadResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *RoomInvitationPayloadResponse) GetInvitation() string {
	if m != nil {
		return m.Invitation
	}
	return ""
}

func (m *RoomInvitationPayloadResponse) GetReceiverId() string {
	if m != nil {
		return m.ReceiverId
	}
	return ""
}

type RoomInvitationAcceptRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInvitationAcceptRequest) Reset()         { *m = RoomInvitationAcceptRequest{} }
func (m *RoomInvitationAcceptRequest) String() string { return proto.CompactTextString(m) }
func (*RoomInvitationAcceptRequest) ProtoMessage()    {}
func (*RoomInvitationAcceptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b96d9038b90c638, []int{2}
}

func (m *RoomInvitationAcceptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInvitationAcceptRequest.Unmarshal(m, b)
}
func (m *RoomInvitationAcceptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInvitationAcceptRequest.Marshal(b, m, deterministic)
}
func (m *RoomInvitationAcceptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInvitationAcceptRequest.Merge(m, src)
}
func (m *RoomInvitationAcceptRequest) XXX_Size() int {
	return xxx_messageInfo_RoomInvitationAcceptRequest.Size(m)
}
func (m *RoomInvitationAcceptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInvitationAcceptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInvitationAcceptRequest proto.InternalMessageInfo

func (m *RoomInvitationAcceptRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RoomInvitationAcceptResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInvitationAcceptResponse) Reset()         { *m = RoomInvitationAcceptResponse{} }
func (m *RoomInvitationAcceptResponse) String() string { return proto.CompactTextString(m) }
func (*RoomInvitationAcceptResponse) ProtoMessage()    {}
func (*RoomInvitationAcceptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b96d9038b90c638, []int{3}
}

func (m *RoomInvitationAcceptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInvitationAcceptResponse.Unmarshal(m, b)
}
func (m *RoomInvitationAcceptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInvitationAcceptResponse.Marshal(b, m, deterministic)
}
func (m *RoomInvitationAcceptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInvitationAcceptResponse.Merge(m, src)
}
func (m *RoomInvitationAcceptResponse) XXX_Size() int {
	return xxx_messageInfo_RoomInvitationAcceptResponse.Size(m)
}
func (m *RoomInvitationAcceptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInvitationAcceptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInvitationAcceptResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RoomInvitationPayloadRequest)(nil), "wechaty.puppet.RoomInvitationPayloadRequest")
	proto.RegisterType((*RoomInvitationPayloadResponse)(nil), "wechaty.puppet.RoomInvitationPayloadResponse")
	proto.RegisterType((*RoomInvitationAcceptRequest)(nil), "wechaty.puppet.RoomInvitationAcceptRequest")
	proto.RegisterType((*RoomInvitationAcceptResponse)(nil), "wechaty.puppet.RoomInvitationAcceptResponse")
}

func init() { proto.RegisterFile("room_invitation.proto", fileDescriptor_3b96d9038b90c638) }

var fileDescriptor_3b96d9038b90c638 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0xaf, 0xd3, 0x30,
	0x10, 0x54, 0xf2, 0xde, 0x6b, 0x89, 0x0b, 0x3d, 0x58, 0x80, 0x2c, 0x68, 0x4b, 0xc8, 0x29, 0x97,
	0x24, 0x12, 0x48, 0xdc, 0x81, 0x53, 0x84, 0x90, 0x50, 0x90, 0x38, 0x70, 0xa9, 0x9c, 0x64, 0x9b,
	0x5a, 0x6a, 0xb2, 0xc6, 0xde, 0xb4, 0xea, 0x8f, 0xe1, 0xbf, 0xa2, 0xc6, 0x49, 0xf9, 0x52, 0x4f,
	0xf6, 0xce, 0x8c, 0x77, 0xbc, 0x1f, 0xec, 0x99, 0x41, 0x6c, 0xb7, 0xaa, 0x3b, 0x2a, 0x92, 0xa4,
	0xb0, 0x4b, 0xb5, 0x41, 0x42, 0xbe, 0x3c, 0x41, 0xb5, 0x97, 0x74, 0x4e, 0x75, 0xaf, 0x35, 0xd0,
	0x8b, 0x4d, 0x83, 0xd8, 0x1c, 0x20, 0x1b, 0xd8, 0xb2, 0xdf, 0x65, 0x27, 0x23, 0xb5, 0x06, 0x63,
	0x9d, 0x3e, 0xda, 0xb1, 0x55, 0x81, 0xd8, 0xe6, 0xd7, 0x3c, 0x5f, 0xe4, 0xf9, 0x80, 0xb2, 0x2e,
	0xe0, 0x47, 0x0f, 0x96, 0xf8, 0x92, 0xf9, 0xaa, 0x16, 0x5e, 0xe8, 0xc5, 0x41, 0xe1, 0xab, 0x9a,
	0xbf, 0x63, 0x73, 0xed, 0x14, 0xc2, 0x0f, 0xbd, 0x78, 0xf1, 0x66, 0x95, 0x3a, 0x87, 0x74, 0x72,
	0x48, 0xbf, 0x92, 0x51, 0x5d, 0xf3, 0x4d, 0x1e, 0x7a, 0x28, 0x26, 0x71, 0xf4, 0xd3, 0x67, 0xeb,
	0x1b, 0x46, 0x56, 0x63, 0x67, 0xe1, 0x3f, 0xa7, 0x35, 0x63, 0x43, 0x75, 0x60, 0xb6, 0xca, 0x99,
	0x05, 0x45, 0x30, 0x22, 0x79, 0xcd, 0x9f, 0xb2, 0x07, 0x42, 0xad, 0x2a, 0x71, 0x37, 0x30, 0x2e,
	0xe0, 0xaf, 0xd9, 0xe3, 0x16, 0xda, 0x12, 0xcc, 0xb6, 0xc2, 0xbe, 0x23, 0x71, 0x1f, 0x7a, 0xf1,
	0x93, 0x62, 0xe1, 0xb0, 0x8f, 0x17, 0xe8, 0x92, 0x77, 0x94, 0xa8, 0xda, 0x8a, 0x87, 0xf0, 0xee,
	0x92, 0xd7, 0x21, 0x79, 0x6d, 0xf9, 0x8a, 0x05, 0xa4, 0x5a, 0xb0, 0x24, 0x5b, 0x2d, 0x66, 0xa1,
	0x17, 0xdf, 0x17, 0xbf, 0x01, 0xfe, 0x9c, 0xcd, 0xe4, 0x51, 0x92, 0x34, 0x62, 0x3e, 0xd8, 0x8e,
	0x11, 0xdf, 0x8c, 0x9f, 0x1d, 0x2a, 0x13, 0x8f, 0x06, 0xee, 0x0f, 0x84, 0xbf, 0x62, 0x0b, 0x03,
	0x15, 0xa8, 0xa3, 0xab, 0x26, 0x70, 0x82, 0x09, 0xca, 0xeb, 0x28, 0x61, 0x2f, 0xff, 0x6e, 0xcf,
	0xfb, 0xaa, 0x02, 0x4d, 0x37, 0xc6, 0x10, 0x6d, 0xfe, 0x1d, 0xdb, 0x24, 0x77, 0xcd, 0xfc, 0xf0,
	0xf9, 0xfb, 0xa7, 0x46, 0xd1, 0xbe, 0x2f, 0xd3, 0x0a, 0xdb, 0x6c, 0xdc, 0x89, 0xac, 0xc1, 0x64,
	0xba, 0x8e, 0x67, 0xe2, 0xd6, 0x24, 0xd9, 0xa3, 0x25, 0x05, 0x59, 0x03, 0x1d, 0x18, 0x49, 0x70,
	0x7d, 0xe1, 0xe8, 0x72, 0x36, 0x0c, 0xf7, 0xed, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x38,
	0x5a, 0xbe, 0x75, 0x02, 0x00, 0x00,
}
