// Code generated by "stringer -type=FileBoxType"; DO NOT EDIT.

package file_box

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FileBoxTypeUnknown-0]
}

const _FileBoxType_name = "FileBoxTypeUnknown"

var _FileBoxType_index = [...]uint8{0, 18}

func (i FileBoxType) String() string {
	if i >= FileBoxType(len(_FileBoxType_index)-1) {
		return "FileBoxType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FileBoxType_name[_FileBoxType_index[i]:_FileBoxType_index[i+1]]
}
