package wechaty

import (
	"github.com/wechaty/go-wechaty/wechaty-puppet/schemas"
	_interface "github.com/wechaty/go-wechaty/wechaty/interface"
	"github.com/wechaty/go-wechaty/wechaty/user"
	"time"
)

type (
	// EventDong ...
	EventDong func(data string)
	// EventError ...
	EventError func(err error)
	// EventFriendship ...
	EventFriendship func(friendship *user.Friendship)
	// EventHeartbeat ...
	EventHeartbeat func(data string)
	// EventLogin ...
	EventLogin func(user *user.ContactSelf)
	// EventLogout ...
	EventLogout func(user *user.ContactSelf, reason string)
	// EventMessage ...
	EventMessage func(message *user.Message)
	// EventReady ...
	EventReady func()
	// EventRoomInvite ...
	EventRoomInvite func(roomInvitation *user.RoomInvitation)
	// EventRoomJoin ...
	EventRoomJoin func(room *user.Room, inviteeList []_interface.IContact, inviter _interface.IContact, date time.Time)
	// EventRoomLeave ...
	EventRoomLeave func(room *user.Room, leaverList []_interface.IContact, remover _interface.IContact, date time.Time)
	// EventRoomTopic ...
	EventRoomTopic func(room *user.Room, newTopic string, oldTopic string, changer _interface.IContact, date time.Time)
	// EventScan ...
	EventScan func(qrCode string, status schemas.ScanStatus, data string)
	// EventStart ...
	EventStart func()
	// EventStop ...
	EventStop func()
)
